version = 0.1

[default.deploy.parameters]
stack_name = "TODO-APP"
resolve_s3 = true
s3_prefix = "TODO-APP"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []